name: rknn_vlm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openjpeg=2.5.4
  - openssl=3.5.4
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - python=3.10.18
  - python_abi=3.10
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.4
      - click==8.3.0
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - datasets==4.1.1
      - dill==0.4.0
      - einops==0.8.1
      - fast-histogram==0.14
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fsspec==2025.9.0
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - idna==3.10
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - markupsafe==3.0.3
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.16.1
      - onnxruntime==1.23.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - protobuf==4.25.4
      - pyarrow==21.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - rkllm-toolkit==1.2.2
      - rknn-toolkit2==2.3.2
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - safetensors==0.6.2
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.55.2
      - triton==3.2.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
prefix: /home/paiworker1/miniconda3/envs/rknn_vlm
